#!/usr/bin/env python3
from tkinter import *
import math
mwin=Tk()
mwin.title("CALCULATOR")
con1=StringVar()
con2=StringVar()
def bh(p):
 if p=='=':
  con1.set(eval(con1.get()))
 elif p=='<-':
  con1.set(con1.get()[:-1])
 elif p=='sqrt':
  con1.set(math.sqrt(eval(con1.get())))
 elif p=='%':
  con1.set((eval(con1.get()))/100)
 elif p=='^':
  con1.set(eval(int(con1.get()) ** int(con2.get())))
 else:
  con1.set(con1.get()+p)
 if p=='c':
  con1.set("")
b0=Button(mwin,text="0",command=lambda : bh('0'))
b1=Button(mwin,text="1",command=lambda : bh('1'))
b2=Button(mwin,text="2",command=lambda : bh('2'))
b3=Button(mwin,text="3",command=lambda : bh('3'))
b4=Button(mwin,text="4",command=lambda : bh('4'))
b5=Button(mwin,text="5",command=lambda : bh('5'))
b6=Button(mwin,text="6",command=lambda : bh('6'))
b7=Button(mwin,text="7",command=lambda : bh('7'))
b8=Button(mwin,text="8",command=lambda : bh('8'))
b9=Button(mwin,text="9",command=lambda : bh('9'))
bp=Button(mwin,text="+",command=lambda : bh('+'))
bs=Button(mwin,text="-",command=lambda : bh('-'))
bd=Button(mwin,text="/",command=lambda : bh('/'))
bm=Button(mwin,text="*",command=lambda : bh('*'))
bpr=Button(mwin,text="%",command=lambda : bh('%'))
br=Button(mwin,text="^",command=lambda : bh('^'))
brt=Button(mwin,text="sqrt",command=lambda : bh('sqrt'))
be=Button(mwin,text="=",command=lambda : bh('='))
br1=Button(mwin,text=")",command=lambda : bh(')'))
br2=Button(mwin,text="(",command=lambda : bh('('))
bdt=Button(mwin,text=".",command=lambda : bh('.'))
bc=Button(mwin,text="c",command=lambda : bh('c'))
bsp=Button(mwin,text="<-",command=lambda : bh('<-'))
e1=Entry(mwin,textvariable=con1)
con1.set("")
e1.grid(row=0,columnspan=4)
b1.grid(row=1,column=0)
b2.grid(row=1,column=1)
b3.grid(row=1,column=2)
b4.grid(row=2,column=0)
b5.grid(row=2,column=1)
b6.grid(row=2,column=2)
b7.grid(row=3,column=0)
b8.grid(row=3,column=1)
b9.grid(row=3,column=2)
bp.grid(row=1,column=3)
bs.grid(row=1,column=4)
bd.grid(row=2,column=3)
bm.grid(row=2,column=4)
bpr.grid(row=3,column=3)
br.grid(row=3,column=4)
b0.grid(row=4,column=0)
bdt.grid(row=4,column=1)
br2.grid(row=4,column=2)
br1.grid(row=4,column=3)
brt.grid(row=4,column=4)
bsp.grid(row=5,column=0)
bc.grid(row=5,column=1)
be.grid(row=5,column=2,columnspan=4,sticky='NSEW')
mwin.mainloop()
